#!/usr/bin/env python3
"""Generate test images for Kitty Graphics Protocol tests.

Outputs base64-encoded PNG/RGB data as shell variables to tests/test-images.sh
"""

import struct
import zlib
import base64
import os

def make_png_rgb(pixels, width, height):
    ihdr_data = struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0)
    ihdr_crc = zlib.crc32(b'IHDR' + ihdr_data) & 0xffffffff
    ihdr = struct.pack('>I', 13) + b'IHDR' + ihdr_data + struct.pack('>I', ihdr_crc)
    raw_data = b''
    for y in range(height):
        raw_data += b'\x00'
        for x in range(width):
            idx = (y * width + x) * 3
            raw_data += pixels[idx:idx+3]
    compressed = zlib.compress(raw_data, 9)
    idat_crc = zlib.crc32(b'IDAT' + compressed) & 0xffffffff
    idat = struct.pack('>I', len(compressed)) + b'IDAT' + compressed + struct.pack('>I', idat_crc)
    iend_crc = zlib.crc32(b'IEND') & 0xffffffff
    iend = struct.pack('>I', 0) + b'IEND' + struct.pack('>I', iend_crc)
    return b'\x89PNG\r\n\x1a\n' + ihdr + idat + iend

def b64png(pixels, w, h):
    return base64.b64encode(make_png_rgb(pixels, w, h)).decode()

# 1. Solid colors (32x32)
def solid(r, g, b, size=32):
    return bytearray([r, g, b] * size * size)

# 2. Red-Blue gradient (128x64)
w, h = 128, 64
gradient_px = bytearray()
for y in range(h):
    for x in range(w):
        r = int(255 * (1 - x/w))
        b = int(255 * x/w)
        g = int(80 * (1 - abs(2*y/h - 1)))
        gradient_px += bytes([r, g, b])

# 3. Checkerboard (64x64, 8x8 cells)
w, h = 64, 64
checker_px = bytearray()
for y in range(h):
    for x in range(w):
        if ((x // 8) + (y // 8)) % 2 == 0:
            checker_px += b'\xff\xff\xff'
        else:
            checker_px += b'\x40\x40\x40'

# 4. Color bars (128x32)
w, h = 128, 32
colors = [(255,255,255),(255,255,0),(0,255,255),(0,255,0),(255,0,255),(255,0,0),(0,0,255),(0,0,0)]
bars_px = bytearray()
bar_w = w // len(colors)
for y in range(h):
    for x in range(w):
        c = colors[min(x // bar_w, len(colors)-1)]
        bars_px += bytes(c)

# 5. Circle icon (32x32)
w, h = 32, 32
icon_px = bytearray()
cx, cy, radius = 15.5, 15.5, 12
for y in range(h):
    for x in range(w):
        dist = ((x - cx)**2 + (y - cy)**2)**0.5
        if dist < radius:
            icon_px += bytes([255, 140, 0])
        else:
            icon_px += bytes([30, 30, 30])

# 6. zlib compressed RGB gradient (64x64)
w, h = 64, 64
zlib_raw = bytearray()
for y in range(h):
    for x in range(w):
        zlib_raw += bytes([int(255*x/w), int(255*y/h), 128])
zlib_grad = base64.b64encode(zlib.compress(bytes(zlib_raw))).decode()

# Write output
out_dir = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(out_dir, "test-images.sh")

with open(out_path, 'w') as f:
    f.write("#!/bin/bash\n")
    f.write("# Auto-generated by generate-test-images.py — do not edit\n\n")
    f.write(f'IMG_RED="{b64png(solid(255, 60, 60), 32, 32)}"\n')
    f.write(f'IMG_BLUE="{b64png(solid(60, 60, 255), 32, 32)}"\n')
    f.write(f'IMG_GREEN="{b64png(solid(60, 200, 60), 32, 32)}"\n')
    f.write(f'IMG_GRADIENT="{b64png(gradient_px, 128, 64)}"\n')
    f.write(f'IMG_CHECKER="{b64png(checker_px, 64, 64)}"\n')
    f.write(f'IMG_BARS="{b64png(bars_px, 128, 32)}"\n')
    f.write(f'IMG_ICON="{b64png(icon_px, 32, 32)}"\n')
    f.write(f'IMG_ZLIB_GRAD="{zlib_grad}"\n')

    # Larger images for performance testing (320x240)
    # Landscape with sky gradient + green ground + sun
    w, h = 320, 240
    landscape_px = bytearray()
    sun_cx, sun_cy, sun_r = 260, 50, 30
    for y in range(h):
        for x in range(w):
            sun_dist = ((x - sun_cx)**2 + (y - sun_cy)**2)**0.5
            if sun_dist < sun_r:
                # Sun (yellow-white)
                t = sun_dist / sun_r
                landscape_px += bytes([255, int(255 - 30*t), int(200 - 100*t)])
            elif y < h * 0.6:
                # Sky gradient (light blue -> deep blue)
                t = y / (h * 0.6)
                r = int(135 - 80*t)
                g = int(206 - 100*t)
                b = int(235 - 50*t)
                landscape_px += bytes([r, g, b])
            elif y < h * 0.65:
                # Horizon haze
                t = (y - h*0.6) / (h*0.05)
                landscape_px += bytes([int(55 + 40*(1-t)), int(106 + 80*(1-t)), int(40 + 50*(1-t))])
            else:
                # Ground (green with texture)
                noise = ((x * 7 + y * 13) % 30) - 15
                t = (y - h*0.65) / (h*0.35)
                g = int(120 - 50*t + noise)
                r = int(40 - 15*t + noise//2)
                b = int(20 - 10*t + noise//3)
                landscape_px += bytes([max(0,min(255,r)), max(0,min(255,g)), max(0,min(255,b))])
    f.write(f'IMG_LANDSCAPE="{b64png(landscape_px, 320, 240)}"\n')

    # Noise pattern (320x240) — worst case for compression
    import random
    random.seed(42)
    w, h = 320, 240
    noise_px = bytearray(random.getrandbits(8) for _ in range(w * h * 3))
    f.write(f'IMG_NOISE="{b64png(bytes(noise_px), 320, 240)}"\n')

print(f"Generated: {out_path}")
