#!/bin/bash
# Kitty Graphics Protocol - Comprehensive Test Suite
# Run on bcon (or any Kitty Graphics-capable terminal)
#
# Usage: bash tests/kitty-graphics-test.sh
#
# Requires: tests/test-images.sh (generated by tests/generate-test-images.py)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/test-images.sh"

# Colors
C_RED='\033[31m'
C_GREEN='\033[32m'
C_YELLOW='\033[33m'
C_CYAN='\033[36m'
C_BOLD='\033[1m'
C_RESET='\033[0m'

pause() {
    echo ""
    echo -e "${C_YELLOW}  >>> Press Enter to continue <<<${C_RESET}"
    read -r
}

section() {
    printf '\033[2J\033[H'
    echo ""
    echo -e "${C_CYAN}${C_BOLD}  $1${C_RESET}"
    echo -e "${C_CYAN}  ────────────────────────────────────────────${C_RESET}"
    echo ""
}

cleanup() {
    printf '\033_Ga=d,d=A,q=2\033\\'
    printf '\033[2J\033[H'
}

# Send image: send_img <id> <png_data> [extra_params]
send_img() {
    printf '\033_Ga=T,i=%d,f=100,q=2%s;%s\033\\' "$1" "${3:+,$3}" "$2"
}

# Transmit only (no display): tx_img <id> <png_data>
tx_img() {
    printf '\033_Ga=t,i=%d,f=100,q=2;%s\033\\' "$1" "$2"
}

# Display previously transmitted: display_img <id>
display_img() {
    printf '\033_Ga=p,i=%d,q=2\033\\' "$1"
}

# Move cursor: move <row> <col> (1-based)
move() {
    printf '\033[%d;%dH' "$1" "$2"
}

cleanup

########################################################################
section "1. Basic Image Display (a=T)"
########################################################################

echo "  Displaying various images using a=T (transmit+display):"
echo ""
move 4 3
send_img 1 "$IMG_GRADIENT"
move 4 40
send_img 2 "$IMG_CHECKER"
move 4 60
send_img 3 "$IMG_BARS"
move 12 3
send_img 4 "$IMG_ICON"
move 12 15
send_img 5 "$IMG_RED"
move 12 25
send_img 6 "$IMG_BLUE"
move 12 35
send_img 7 "$IMG_GREEN"

move 18 3
echo -e "  ${C_GREEN}Expected: gradient(128x64), checkerboard(64x64), color bars(128x32)${C_RESET}"
echo -e "  ${C_GREEN}          circle icon, red/blue/green squares${C_RESET}"
pause
cleanup

########################################################################
section "2. Transmit then Display (a=t + a=p)"
########################################################################

echo "  Transmitting landscape (320x240) without display..."
tx_img 10 "$IMG_LANDSCAPE"
echo "  (nothing should appear)"
pause

echo "  Now displaying with a=p..."
move 5 3
display_img 10
move 20 3
echo -e "  ${C_GREEN}Expected: Landscape image (320x240) with sky, sun, and ground${C_RESET}"
pause
cleanup

########################################################################
section "3. Large Image Performance"
########################################################################

echo "  Displaying 320x240 landscape..."
move 3 3
send_img 20 "$IMG_LANDSCAPE"

move 20 3
echo -e "  ${C_GREEN}Expected: Landscape (320x240) rendered without noticeable delay${C_RESET}"
pause

echo ""
echo "  Displaying 320x240 noise (worst case for compression)..."
move 3 50
send_img 21 "$IMG_NOISE"

move 22 3
echo -e "  ${C_GREEN}Expected: Random noise pattern next to landscape${C_RESET}"
pause
cleanup

########################################################################
section "4. Delete All — Default (a=d, no d= parameter)"
########################################################################

move 3 3
send_img 30 "$IMG_GRADIENT"
move 3 40
send_img 31 "$IMG_CHECKER"
move 10 3
send_img 32 "$IMG_LANDSCAPE"

move 20 3
echo "  3 images displayed. Sending: a=d (default = delete all)"
pause

printf '\033_Ga=d,q=2\033\\'
sleep 0.1
move 21 3
echo -e "  ${C_GREEN}Expected: All images gone${C_RESET}"
pause
cleanup

########################################################################
section "5. d=a (lowercase) vs d=A (uppercase)"
########################################################################

echo "  --- 5a: d=a removes placements, keeps data ---"
move 4 3
send_img 40 "$IMG_BARS"
move 10 3
echo "  Color bars displayed. Deleting with d=a..."
printf '\033_Ga=d,d=a,q=2\033\\'
sleep 0.1
echo "  Bars gone. Re-displaying with a=p..."
move 12 3
display_img 40
move 16 3
echo -e "  ${C_GREEN}Expected: Bars reappear (data kept in cache)${C_RESET}"
pause
cleanup

echo "  --- 5b: d=A removes placements AND data ---"
move 4 3
send_img 41 "$IMG_BARS"
move 10 3
echo "  Deleting with d=A..."
printf '\033_Ga=d,d=A,q=2\033\\'
sleep 0.1
echo "  Trying re-display with a=p..."
move 12 3
display_img 41
move 16 3
echo -e "  ${C_GREEN}Expected: Nothing reappears (data freed)${C_RESET}"
pause
cleanup

########################################################################
section "6. Delete by ID (d=i)"
########################################################################

move 3 3
echo -n "Gradient(50): "
send_img 50 "$IMG_GRADIENT"
move 3 40
echo -n "Checker(51): "
send_img 51 "$IMG_CHECKER"
move 10 3
echo -n "Bars(52): "
send_img 52 "$IMG_BARS"

move 16 3
echo "  Deleting id=51 (checker) with d=i..."
pause

printf '\033_Ga=d,d=i,i=51,q=2\033\\'
sleep 0.1
move 17 3
echo -e "  ${C_GREEN}Expected: Checker gone, gradient and bars remain${C_RESET}"
pause
cleanup

########################################################################
section "7. Delete at Cursor Position (d=c)"
########################################################################

move 3 5
send_img 60 "$IMG_RED"
move 3 25
send_img 61 "$IMG_BLUE"
move 3 45
send_img 62 "$IMG_GREEN"

move 10 3
echo "  Three squares. Cursor will move to blue and delete with d=c..."
pause

move 3 25
printf '\033_Ga=d,d=c,q=2\033\\'
sleep 0.1
move 11 3
echo -e "  ${C_GREEN}Expected: Blue gone, red and green remain${C_RESET}"
pause
cleanup

########################################################################
section "8. Delete by Column (d=x) and Row (d=y)"
########################################################################

move 3 5
send_img 70 "$IMG_RED"
move 3 25
send_img 71 "$IMG_BLUE"
move 8 5
send_img 72 "$IMG_GREEN"
move 8 25
send_img 73 "$IMG_ICON"

move 14 3
echo "  4 images in a grid. Deleting column 5 with d=x..."
pause

printf '\033_Ga=d,d=x,x=5,q=2\033\\'
sleep 0.1
move 15 3
echo -e "  ${C_GREEN}Expected: Red(3,5) and Green(8,5) gone. Blue(3,25) and Icon(8,25) remain${C_RESET}"
pause
cleanup

move 3 5
send_img 80 "$IMG_RED"
move 3 25
send_img 81 "$IMG_BLUE"
move 8 5
send_img 82 "$IMG_GREEN"
move 8 25
send_img 83 "$IMG_ICON"

move 14 3
echo "  4 images in a grid. Deleting row 3 with d=y..."
pause

printf '\033_Ga=d,d=y,y=3,q=2\033\\'
sleep 0.1
move 15 3
echo -e "  ${C_GREEN}Expected: Red(3,5) and Blue(3,25) gone. Green(8,5) and Icon(8,25) remain${C_RESET}"
pause
cleanup

########################################################################
section "9. Delete at Cell Coordinate (d=p)"
########################################################################

move 4 10
send_img 90 "$IMG_GRADIENT"
move 4 50
send_img 91 "$IMG_CHECKER"

move 14 3
echo "  Gradient at (4,10), Checker at (4,50). Deleting at (4,10)..."
pause

printf '\033_Ga=d,d=p,x=10,y=4,q=2\033\\'
sleep 0.1
move 15 3
echo -e "  ${C_GREEN}Expected: Gradient gone, checker remains${C_RESET}"
pause
cleanup

########################################################################
section "10. Screen Clear (ESC[2J) Removes Images"
########################################################################

move 3 3
send_img 100 "$IMG_LANDSCAPE"
move 3 50
send_img 101 "$IMG_CHECKER"

move 20 3
echo "  Two images. Clearing screen..."
pause

printf '\033[2J\033[H'
echo ""
echo -e "  ${C_GREEN}Expected: Screen clear, all images gone${C_RESET}"
pause
cleanup

########################################################################
section "11. zlib Compression (o=z)"
########################################################################

echo "  Sending 64x64 RGB gradient with zlib compression..."
move 4 3
printf '\033_Ga=T,i=110,f=24,s=64,v=64,o=z,q=2;%s\033\\' "$IMG_ZLIB_GRAD"

move 12 3
echo -e "  ${C_GREEN}Expected: Color gradient square (red-green with purple tint)${C_RESET}"
pause
cleanup

########################################################################
section "12. Chunked Transfer (m=1, m=0)"
########################################################################

echo "  Sending landscape in 2 chunks..."
HALF=$(( ${#IMG_LANDSCAPE} / 2 ))
# Ensure first chunk is multiple of 4 (base64 alignment)
HALF=$(( (HALF / 4) * 4 ))
CHUNK1="${IMG_LANDSCAPE:0:$HALF}"
CHUNK2="${IMG_LANDSCAPE:$HALF}"

move 4 3
printf '\033_Ga=T,i=120,f=100,q=2,m=1;%s\033\\' "$CHUNK1"
printf '\033_Gm=0,q=2;%s\033\\' "$CHUNK2"

move 20 3
echo -e "  ${C_GREEN}Expected: Landscape assembled from 2 chunks${C_RESET}"
pause
cleanup

########################################################################
section "13. Query Support (a=q)"
########################################################################

echo "  Sending query (a=q, q=0)..."
echo ""
printf '\033_Ga=q,i=130,f=100,q=0;%s\033\\' "$IMG_RED"
sleep 0.5
echo ""
echo ""
echo -e "  ${C_GREEN}Expected: Response like ESC_Gi=130;OK${C_RESET}"
echo "  (may appear as raw characters in the terminal)"
pause
cleanup

########################################################################
section "14. Multiple Images Same Position (overwrite)"
########################################################################

echo "  Displaying red, then blue, then green at same position..."
move 4 3
send_img 140 "$IMG_RED"
sleep 0.3
move 4 3
send_img 141 "$IMG_BLUE"
sleep 0.3
move 4 3
send_img 142 "$IMG_GREEN"

move 10 3
echo -e "  ${C_GREEN}Expected: Green square visible (last one drawn)${C_RESET}"
pause
cleanup

########################################################################
section "15. Rapid Image Updates (same ID, like Xkitty)"
########################################################################

echo "  Sending 20 frames to same ID (simulating Xkitty)..."
move 4 3
for i in $(seq 1 20); do
    send_img 150 "$IMG_RED"
    send_img 150 "$IMG_BLUE"
    send_img 150 "$IMG_GREEN"
done

move 10 3
echo -e "  ${C_GREEN}Expected: No freeze, final image visible${C_RESET}"
echo "  (60 image uploads to same id=150)"
pause
cleanup

########################################################################
printf '\033[2J\033[H'
section "All Tests Complete"
########################################################################

echo ""
echo "  Summary of features tested:"
echo "    1.  a=T (transmit+display)"
echo "    2.  a=t + a=p (transmit then display)"
echo "    3.  Large image (320x240)"
echo "    4.  a=d default (delete all)"
echo "    5.  d=a vs d=A (lowercase/uppercase)"
echo "    6.  d=i (delete by ID)"
echo "    7.  d=c (delete at cursor)"
echo "    8.  d=x, d=y (delete by column/row)"
echo "    9.  d=p (delete at coordinate)"
echo "    10. ESC[2J clears images"
echo "    11. zlib compression (o=z)"
echo "    12. Chunked transfer (m=1/m=0)"
echo "    13. Query (a=q)"
echo "    14. Overwrite at same position"
echo "    15. Rapid updates (same ID)"
echo ""
echo "  Run 'reset' if display is corrupted."
echo ""
